name = "km-technologies"
compatibility_date = "2025-01-01"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "km-it-services-db"
database_id = "400fdca8-cc6f-4451-844d-53ad24bd06a5"
preview_database_id = "400fdca8-cc6f-4451-844d-53ad24bd06a5"

# Default environment vars (used for local dev `npm run dev` and fallback)
[vars]
JWT_SECRET = "km-it-services-secret-key-2026"
ADMIN_EMAIL = "admin@kmsoftware.com"
RESEND_API_KEY = "re_your_api_key_here"

# Production environment vars (used when you push to your main/master branch)
[env.production.vars]
JWT_SECRET = "km-it-services-secret-key-2026-production"
ADMIN_EMAIL = "admin@kmsoftware.com"
RESEND_API_KEY = "re_your_api_key_here"

# Preview environment vars (used for any preview deployments and other branches)
[env.preview.vars]
JWT_SECRET = "km-it-services-secret-key-2026-preview"
ADMIN_EMAIL = "admin@kmsoftware.com"
RESEND_API_KEY = "re_your_api_key_here"
