<template>
  <div class="min-h-screen bg-base-100 pt-32 pb-24">
    <div class="container mx-auto px-4 sm:px-6 lg:px-8 max-w-4xl">
      
      <!-- Header -->
      <div class="mb-12 border-b border-base-content/10 pb-8">
        <h1 class="text-4xl sm:text-5xl font-black tracking-tight text-base-content mb-4">
          Privacy Policy
        </h1>
        <p class="text-base-content/60 text-sm">
          Effective Date: February 21, 2026
        </p>
      </div>

      <!-- Content -->
      <div class="prose prose-base-content prose-h2:text-2xl prose-h2:font-bold prose-h2:mt-10 prose-h2:mb-4 prose-p:text-base-content/80 prose-li:text-base-content/80 max-w-none">
        
        <p class="lead text-lg">
          At KM Software's ("we," "our," or "us"), your privacy is deeply important to us. This Privacy Policy outlines the types of personal information that is received and collected by our services, and how it is used.
        </p>

        <h2>1. Information We Collect</h2>
        <p>
          We collect varying types of data in order to provide and improve our software engineering, web development, and digital consulting services:
        </p>
        <ul class="list-disc pl-6 space-y-2 mt-4">
          <li><strong>Personal Identification Information:</strong> Name, email address, phone number, and company details you provide via our contact forms.</li>
          <li><strong>Service Data:</strong> Project briefs, technical specifications, and internal documents explicitly shared during consultations.</li>
          <li><strong>Automated Data:</strong> IP addresses, browser types, timestamps, and log data generated by interacting with our web platform.</li>
        </ul>

        <h2>2. How We Use Your Information</h2>
        <p>
          We use the information we collect strictly to deliver top-tier digital products and ensure excellent client communication. Specifically:
        </p>
        <ul class="list-disc pl-6 space-y-2 mt-4">
          <li>To establish contact regarding your project inquiries.</li>
          <li>To construct and format project proposals, contracts, and software architecture plans.</li>
          <li>To improve the usability, performance, and accessibility of our own platform.</li>
          <li>To comply with regulatory standards and SOC 2 / GDPR requirements where applicable.</li>
        </ul>

        <h2>3. Data Protection and Security</h2>
        <p>
          We implement rigorous, zero-trust security measures to maintain the safety of your personal information. Your data is encrypted at rest and in transit. Access to sensitive project information is strictly restricted to the engineers and project managers directly assigned to your account.
        </p>

        <h2>4. Third-Party Sharing</h2>
        <p>
          We <strong>do not</strong> sell, trade, or rent your personal identification information to outside entities. We may share generic aggregated demographic information not linked to any personal identification with trusted partners for statistical analysis.
        </p>

        <h2>5. Your Data Rights</h2>
        <p>
          Depending on your location (e.g., GDPR in Europe, CCPA in California), you have specific rights regarding your data:
        </p>
        <ul class="list-disc pl-6 space-y-2 mt-4">
          <li>The right to access the data we have collected about you.</li>
          <li>The right to request immediate erasure of your data ("Right to be Forgotten").</li>
          <li>The right to withdraw consent for any marketing communications.</li>
        </ul>

        <h2>6. Contacting Us</h2>
        <p>
          If you have any questions regarding this Privacy Policy or wish to exercise your data rights, please contact our Compliance Officer at:
        </p>
        <div class="bg-base-200/50 p-6 rounded-xl border border-base-content/5 mt-6">
          <p class="font-bold text-primary mb-1">KM Software's Privacy Team</p>
          <p>Email: <a href="mailto:privacy@kmsoftware.com" class="text-secondary hover:underline">privacy@kmsoftware.com</a></p>
          <p>Address: 123 Tech Street, Silicon Valley, CA 94000</p>
        </div>

      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
useSeoMeta({
  title: 'Privacy Policy | KM Software\'s',
  description: 'Understand how KM Software\'s collects, uses, and protects your personal data.',
})
</script>
